let Mini_cheddar = sprites.create(assets.image`myImage`, SpriteKind.Player)
controller.moveSprite(Mini_cheddar, 100, 0)
let mySprite2 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . e e . . . . . . . . 
    . . . . . . e e e . . . . . . . 
    . . . . . e f f e e e . . . . . 
    . . . . . e f e e e e . . . . . 
    . . . . . e f e e e e . . . . . 
    . . . e e e e e e e e e e . . . 
    . . e e f f e e e e e e e . . . 
    . e e f f e e e e e e e e . . . 
    . e e f f f e e e e e e e e e . 
    . e e f f e e e e e e e e e e . 
    . e e f f e e e e e e e e e . . 
    . e e f e e e e e e e e e e . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
game.splash("Crisp", "Invaders")
scene.setBackgroundImage(img`
    fff...............fffffffffffffffffffffffffffffff...............................................................................................................
    fff...fffffffffffffffffffffffffffffffffffffffffff...............................................................................................................
    fffffffffffffffffffffffffffffffffffffffffffffffff...............................................................................................................
    fffffffffffffffffffffffffffffffffffffffffffffffff...............................................................................................................
    fffffffffffffffffffffffffffffffffffffffffffffffff...............................................................................................................
    fffffffffffffffffffffffffffffffffffffffffffffffff...............................................................................................................
    fffffffffffffffffffffffffffffffffffffffffffffffff....................................ffffffffffffffffffffffffffffffffffffffffffffff.............................
    fff...fffffffffffffffffffffffffffffffffffffff........fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..
    fff2..ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..
    fff2..ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..
    fff.2.2.....ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..
    fff.22......fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...........2.......................ffffffffffffffffffffffffffffffffff..
    fff..2.........2.fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff......2................fffffffffffffffffffffffffffffffffffff......
    fff..2..........2ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..........fffffffffffffffffffffffffffffffffffff............
    fff.2.2.........2ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...................
    fff.2..2.........2...fffffffffffffff...fffffffff......................2...ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..........................
    fff.2..2.........2.fffffffffffffff......fffffffff......................2.......2..ffffffffffffffffffffffffffffffffffffffffffffff................................
    ffff....2........2.ffffffffffff..2.......ffffffff......................2......2fffffffffffffffffffffffffffffffffffffffffffffffffffff............................
    ffff....2........2.ffffffffff....2........ffffffff............ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....................
    ffff.....2........2ffffffffff....2.........fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff................
    ffff.....2........2ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.2222222....fffffffffffffffffffffffffffffff................
    ffff......2.....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2222222.......22222....2.ffffffffffffffffffffffff................
    fffff.....2.ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff............22222....22.2.ffffffffffffffff................
    fffff......2ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.........2222.2.2.........ffffffff................
    fffff......2ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.....2..22.2.2...........fffff................
    ffffff.....2ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff................
    ffffff......ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff................
    ffffff......2.........2.......ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff................
    ffffff.......2........2........fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff................
    ffffff.......2.........2........2fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff................
    ffffff........2........2........2......2fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff22222222222222.....2.....22........................
    ffffff........2.........2.......2......2...2.....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.............2.22...2.......2.......................
    ffffffff.......2.........2......2.....ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.....2.........2...222.2.......2......................
    ffffffff.......2..........2ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...................22.....2.........22.....22.......2......................
    ffffffff.......2..ffffffffffffffffffffffffffffffffffffffffffffffffffffffff...22..2......................2.2....2.........22......2222.....2.....................
    ffffffff.......fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..2..2..2..........22......22..22....2................2...
    ffffffff.......fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff................2...
    ffffffff.......fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2...............2...
    fffffffff......fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff22..............2...
    fffffffff......ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.22............2...
    fffffffff.........2...fffffffffff.fffffff.....22222.........ffffffff2...2...22....2..............ffffffffffffffffffffffffffffffffffffffffffff22.22..........2...
    fffffffff.........2..ffffffffff....fffffff..22..2............ffffffff22.2...2.2...2.....ffffffffffffffffffffffffffffffffffffffffffffffffffffff222.2.........2...
    fffffffff..........2ffffffffff.....fffffff.2....2.............ffffffff.fffffffffffffffffffffffffffffffffffffffffffffffffffffffff...2.2ffffffff..22222.......2...
    ffffffffff.........2ffffffff........ffffff2....ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..2...2.....2.2fffffffff.2....22.....2...
    ffffffffff.........ffffffff....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff........2222....2.....22fffffffff.2.....222...2...
    ffffffffff........ffffffff.....ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...2..2.............222..2.....22fffffffff.2......2.2..2...
    ffffffffff.......ffffffff......fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff............2...2............2..2222....22fffffffff.2.......22..2...
    ffffffffff......fffffffff......fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2..fffffffffffffffff...........2.....22...2.fffffffff..2......22..2...
    ffffffffff......ffffffff.......ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....2.....2.22.2.fffffffff..2.......22.2...
    ffffffffff.....ffffffff.........2....fffff.........2.....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.2......2..22.fffff......2........2.2...
    ffffffffff....ffffffff.2.......2....ffffff.........2...............ffffffffffffffffffffffffffffffffffffffffffffffffffffff2......2...22fffff......2........222...
    ffffffffff....fffffff..2.......2...fffffff.........2.................ffffff..ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff......2.........22...
    ffffffffff...ffffffff...2.....2...ffffffff..........2................fffffff....ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..2........22...
    ffffffffff..ffffffff....2.....2..fffffffff..........2.................ffffff....ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..2.........2...
    ffffffffff..fffffff......2....fffffffffff............2................fffffff.........2............fffffffffffffffffffffffffffffffffffffffffffff..2.........22..
    ffffffffff.ffffffff......fffffffffffffff.............2...............2fffffff..........2..........ffffffffffffffffffffffffffffffffffffffffffffff.2..........222.
    ffffffffff2fffffff...ffffffffffffffffff..............2...............2.fffffff..........2....fffffffffffffffffffffff.....fffffffffffffffffffffff.2..........222.
    ffffffffffffffffffffffffffffffffffffff2...............2..............2.fffffff..........ffffffffffffffffffffffff.........2...222...2.2fffff222222222222222222222
    fffffffffffffffffffffffffffffffffffffff...............2..............2..ffffff......fffffffffffffffffffffffff..2.........2......222222fffff.....22.....22222222.
    fffffffffffffffffffffffffffffffffffffffffffffffffffff.2..............2..ffffffffffffffffffffffffffffffffff.....2........2...........2.fffff222222222222.......2.
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.....2...fffffffffffffffffffffffffffff..........2.......2...........2.fffff....2..2............2
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............2.......2............2fffff....2...2...........2
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..2.................2.......2............2fffff...2....2...........2
    ffffffffffffff2...........2..2..2..fffffffffffffffffffffffffffffffffffffffffffffffffffff.......2.................2......2.............fffff...2.....2..........2
    fffffffffffff2............2...2.2.....2..........fffffffffffffffffffffffffffffffffffffffffffff..2................2......2.............fffff...2.....2..........2
    fffffffffffff2............2...2..2....2...fffffffffffffffffffffffffffffffffffffffffffffffffffffffff..............2......2.............fffff..2.......2.........2
    ffffffffffff2.............2....2.2..fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff........2......2.............fffff.2........2.........2
    ffffffffffff2.............2..fffffffffffffffffffffffffffffffffffff...2......fffffffffffffffffffffffffffffffff.....2.....2.............fffff2..........2........2
    ffffffffff.2.2.........ffffffffffffffffffffffffffffffffffff..........2......fffffff.fffffffffffffffffffffffffffff.2.....2.............fffff...........2.......2.
    fffffffff.2..2.ffffffffffffffffffffffffffffffffffffff.....2.........2........ffffff.....22fffffffffffffffffffffffffff...2.............fffff............2.....2..
    fffffffff2fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.222..ffffffffffffffffffffffff.2.............fffff............2....2...
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2.............fffff.............2..2....
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2............2fffff.............2.2.....
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2..........22.fffff.............22......
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.......2...fffff...........222.......
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..2....fffff......22222..2.......
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....fffff..2222.......2.......
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2222fffff22...........2.......
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....fffff.............2.......
    fffffff....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....fffff.............2.......
    fffffff.......ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....fffff.............2.......
    fffffff.......fffffffff....2.fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....ffffff............2.......
    fffffff.......fffffffffff..fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....ffffff............2.......
    fffffff.......ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff......ffffff...........2........
    fffffff........fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.fffffffffffffffffffffffffffffff..
    ffffff...........fffffffffffffffffffffffff.fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..
    ffffff...........2.ffffffffffffffffffffffffffffffff..2..........2fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..
    ffffff............2.ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..
    ffffff............2.ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..
    ffffff............2.ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..........
    ffffff............2.fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2................
    ffffff.............2.....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.22.................
    ffffff.............2.......22................22....2..........ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2....fffff2...................
    ffffff..............2......22.2................22..2...............222fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...2fffff....................
    ffffff..............2.....2..22..................222.............ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff222.fffff....................
    ffffff...............2...2.........................222...........ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....fffff....................
    ffffff2..............2...2........................2...222........fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...fffff....................
    ffffff2...............2.2.........................2......222.....ffffffffffffffffffffffffffffffffffffffffffffffffff..22222....ffffff...fffff....................
    ffffff2...............22..........................2.........22222fffffffffffffffffffffffffffffffffffffffffffffff222222..222...ffffff...fffff....................
    ffffff2..........................................2.................2222222fffffffffffffffffffffff2222222222222..........2..22.fffffff..fffff....................
    ffffff2..........................................2......................22ffffffffffffffffffffffffffffffffffffffffff....2....22ffffff..fffff....................
    ffffff2.........................................2...................222222...ffffffffffffffffffffffffffffffffffffffffffffffffffffffff..fffff....................
    ffffff.2........................................2.............222222..............fffffffffffffffffffffffffffffffffffffffffffffffffff..fffff....................
    ffffff.2.......................................2..............2.........................fffffffffffffffffffffffffffffffffffffffffffff22fffff....................
    ffffff.2.......................................2.............................................ffffffffffffffffffffffffffffffffffffffff..fffff....................
    ffffff.2......................................2.................................................................fffffffffffffffffffff22fffff2...................
    ffffff.2......................................2.........................................................................2..............fffff2222................
    ffffff.2.....................................2..........................................................................2..............fffff.22222..............
    ffffff..2....................................2..........................................................................2..............fffff......2222..........
    ffffff...2..................................2...........................................................................2..............fffff.........2222.......
    ffffff....2................................2............................................................................2..............fffff............222.....
    ffffff.....2.............................22............................................................................................fffff..............2222..
    ffffff......2...........................2..............................................................................................fffff.................222
    ffffff.......22........................2...............................................................................................fffff....................
    ffffff.........22.....................2................................................................................................fffff....................
    ffffff...........22..................2.................................................................................................fffff....................
    fffff..............22..............22..................................................................................................fffff....................
    fffff................22...........2....................................................................................................fffff....................
    fffff..................22222222222.....................................................................................................fffff....................
    fffff...........................................................................................................................................................
    `)
